### PR TITLE
merging landing, contact, about ,sub-event and event page

### PR DESCRIPTION
**Pull request by ahampriyanshu**

### CODE REVIEW

**Comment by Sudhanshu-Dubey14** [comment]
In the "Contact" page you are tell them to "Fill in the form" but there is no form there... is it the one on the landing page?

**Comment by Sudhanshu-Dubey14** [comment]
The i-GNEz in the landing page is written as "I-GNEZ" can you correct that..?

**Comment by Sudhanshu-Dubey14** [comment]
Also the image of Workshop on landing page is blurred on my side... can you correct it?

**Comment by ahampriyanshu** [comment]
All done. And have also created events page.

**Pull request merged**
